# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: Regression Pipeline

trigger: none

jobs:
  - job: JOB1_RUN
    pool:
      vmImage: 'windows-latest'
    workspace:
      clean: all
    steps:
      - task: JavaToolInstaller@0
        displayName: 'Use Java 17'
        inputs:
          versionSpec: 17
          jdkArchitectureOption: x64
          jdkSourceOption: PreInstalled
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
        condition: succeededOrFailed()
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        continueOnError: true
        condition: succeededOrFailed()
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          targetPath: 'target/report'
          artifact: 'My Report'
        continueOnError: true
        condition: succeededOrFailed()